### ISSUE TITLE
Icon Height with No Text

### ISSUE THREAD

**Issue by sarahnyxx** [int128/bntp#13] opened 2019-04-11 10:23 UTC
With untitled bookmarks (Used to save space on my bookmarks bar - trying to find a solution to hide that as often as possible now), the icon gets cut off as the DIV has no idea what height to be without text filling it in. 

Proposal: add `height: 16px;` to the `.TileFolderItem__ButtonBody` class in the CSS, to match the 16px height of the background icon. 

I might get around to this if I find the time to set up a dev environment to pull, edit, push, merge request, etc

**Comment by JaredKat** [comment] 2019-04-11 10:25
Duplicate of #10 sorry about that. Would retract and comment over there, but, permissions... I've just been a bit hasty

**Comment by int128** [comment] 2022-08-18 13:17
Fixed since v3.0.0.

**Closed by int128** 2022-08-18 13:17 UTC
